feat(get-medias/sort): add option to customize sort on getMedias
capacitor-community/media pull request #37
Opened 2023-02-15 21:23 UTC by matheusdavidson

This PR will add the ability to sort `getMedias` using custom keys and ascending.
#36

2023-02-15 21:44 UTC, nkalupahana commented
Thank you so much for your contribution! Two quick things before I review:
- Could you make the two options in `MediaSort` optional? Users may want to specify one but not the other.
- Can you have multiple sort descriptors at a time? If so, it would be great if you could add that functionality; I don't think it would be too hard to add.

Again, thank you for contributing! We really appreciate it.

2023-02-15 21:57 UTC, stewones commented
> Thank you so much for your contribution! Two quick things before I review:
> 
> * Could you make the two options in `MediaSort` optional? Users may want to specify one but not the other.
> * Can you have multiple sort descriptors at a time? If so, it would be great if you could add that functionality; I don't think it would be too hard to add.
> 
> Again, thank you for contributing! We really appreciate it.

agree with point 1. and would make it clear through the doc block what the default value is for both options.

for point 2 I think it could potentially hold off merging this PR. maybe just define a broader type definition that can support multiple sort descriptors in the future without breaking the proposed feature.

2023-02-15 22:09 UTC, stewones commented
looking better at it, I think what @nkalupahana is proposing is to pass an array of keys instead of a string. So I tend to agree and we stay consistent with iOS API.

2023-02-16 01:17 UTC, matheusdavidson commented
Hi @nkalupahana and @stewones, thanks for reviewing.

I agree with both points but on point 1 the key can't be optional after implementing point 2, because being an array to enable multiple sort options, the key is the only important part inside the array, for example, an array of `[{ ascending: false }, { ascending: true }]` wouldn't make sense, but `[{ key: creationDate }, { key: isFavorite }]` makes sense.

So here what I did:
- make sort accept: `string | MediaSort[]`
- when sort is a `string`, it will be used as a key and default `ascending` to `false`.
- when sort is an `array`, it will loop and append to `sortDescriptors`, here the key is required and ascending optional, if one is not provided `true` is used by default.

2023-02-16 01:36 UTC, stewones requested changes

2023-02-16 01:36 UTC, stewones commented on src/definitions.ts
> +  key:
I think instead of string here we could extract this as a separate type (eg: `Descriptor` maybe?) 

```
sort?: Descriptor | MediaSort[]
```

2023-02-16 01:47 UTC, stewones approved these changes
good job, LGTM.

2023-02-16 01:49 UTC, matheusdavidson commented
Sorry @nkalupahana, didn't meant to remove you from review, github only gave me an option to ask @stewones, please review it as well

2023-02-16 20:22 UTC, nkalupahana commented
Looks good! Could you remove the debug prints? Other than that, I think we're good to get this merged :) thanks for your contribution!

2023-02-17 19:24 UTC, matheusdavidson commented
@nkalupahana, @stewones, removed debug print. Should be good to go now.

2023-02-18 16:56 UTC, merged