doc(ios/info): add needed NSPhotoLibraryUsageDescription information
capacitor-community/media pull request #39
Opened 2023-02-17 20:45 UTC by matheusdavidson

Update instructions for IOS to show the needed NSPhotoLibraryUsageDescription key on info.plist.
#38

2023-02-17 20:54 UTC, matheusdavidson commented
This is how it looks:
![image](https://user-images.githubusercontent.com/2229994/219791294-f88ce8b8-0ee3-4754-9f89-05c0b9593e93.png)

2023-02-18 16:58 UTC, nkalupahana requested changes
A few small changes -- thank you!

2023-02-18 16:58 UTC, nkalupahana commented on README.md
> +  <string>Describe why you need access to the library</string>
```suggestion
  <string>Describe why you need access to user's photos</string>
```

2023-02-18 16:58 UTC, nkalupahana commented on README.md
> +- add the following key to `Info.plist.`:
```suggestion
- add the following to `Info.plist`:
```

2023-02-20 15:11 UTC, nkalupahana approved these changes

2023-02-20 15:11 UTC, merged